services:
  jenkins-service:
    build: .
    container_name: jenkins-container
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./volume_mapping/master:/var/jenkins_home