# - over here we are trying to create 2 container (nginx-container & alpine-container) and we will be demonstrating the volume mapping by downloading the content and putting git into out local.
version: "3"
services:
  nginx-container:
    image: nginx
  alpine-container:
     image: alpine
     depends_on:
       - nginx-container
     working_dir: /fileDownload
     entrypoint: "wget http://nginx-container"
     volumes:
       - ./fileSyncFolder:/fileDownload
