version: "3"
services:
  mysql-service:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ashish@123
      MYSQL_USER: ashish
      MYSQL_PASSWORD: ashish@123
      MYSQL_DATABASE: students_db
    ports:
      - 3307:3306
    volumes:
      - ./init_script:/docker-entrypoint-initdb.d
  adminer-service:
    image: adminer
    ports:
      - 8070:8080