
services:
  zookeeper-service:
    image: zookeeper:3.9.3-jre-17
    container_name: zookeeper-container
    ports:
      - "2181:2181"

  kafka-service:
    image: bitnami/kafka:latest
    container_name: kafka-container
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper-service:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka-service:9092
      KAFKA_CFG_BROKER_ID: 1
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper-service

  kafka-ui-service:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui-container
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-service:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper-service:2181
    depends_on:
     - kafka-service